[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

# Neo4j health check
healthcheckPath = "/"
healthcheckTimeout = 300