name: mattersglobal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core dependencies
  - neo4j
  - pydantic
  - numpy
  - websockets
  - openai
  # Web server
  - flask
  - flask-cors
  - gunicorn
  # Utilities
  - python-dotenv
  # Testing
  - pytest
  # Pip dependencies for packages not available in conda or requiring specific versions
  - pip
