name: mattersglobal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # Core dependencies
  - neo4j>=4.4.0
  - pydantic>=2.0.0
  - numpy>=1.20.0
  - websockets>=10.0
  - openai
 # Web server
  - flask>=2.0.0
  - flask-cors>=3.0.0
  - gunicorn>=20.0.0
  # Utilities
  - python-dotenv>=0.19.0
  # Testing
  - pytest>=7.0.0
  # Pip dependencies for packages not available in conda or requiring specific versions
  - pip
 
