"""Reusable matters engine."""

from .engine import (
    as_condition_list,
    condition_label,
    create_condition,
    dependents,
    descendants,
    frontier,
    has_dependency_cycle,
    horizon,
    normalize_conditions,
    prerequisites,
    resolved,
    serialize_condition,
    truth,
    universe,
    unresolved,
)
from .extraction import (
    extract_candidate_matters,
    extraction_proposal,
    propose_dependency_candidates,
    slugify,
)
from .identity import (
    EmbeddingStore,
    FakeEmbedder,
    LocalEmbedder,
    classify_relationship,
    get_embedder,
    ingest_candidates,
    match_candidate,
    reconcile_candidates,
)
from .llm_extraction import (
    build_extraction_proposal,
    llm_extraction_proposal,
)
from .reports import (
    false_condition_labels,
    format_unlock_report,
    propose_action,
    unlock_items,
    unlock_report,
)
from .sharing import PUBLIC, merge_public_state, public_state
from .storage import (
    DEFAULT_STATE_PATH,
    load_state,
    resolve_state_path,
    save_state,
)
from .tots import (
    TotsError,
    build_tots_context,
    build_tots_proposal,
    fit_bradley_terry_davidson,
    reconcile_ordered_judgments,
    schedule_swiss_pairs,
    select_diverse_finalists,
)

__all__ = [
    "DEFAULT_STATE_PATH",
    "EmbeddingStore",
    "FakeEmbedder",
    "LocalEmbedder",
    "PUBLIC",
    "TotsError",
    "as_condition_list",
    "build_extraction_proposal",
    "build_tots_context",
    "build_tots_proposal",
    "classify_relationship",
    "condition_label",
    "create_condition",
    "dependents",
    "descendants",
    "extract_candidate_matters",
    "extraction_proposal",
    "fit_bradley_terry_davidson",
    "get_embedder",
    "ingest_candidates",
    "llm_extraction_proposal",
    "match_candidate",
    "reconcile_candidates",
    "frontier",
    "false_condition_labels",
    "format_unlock_report",
    "has_dependency_cycle",
    "horizon",
    "load_state",
    "merge_public_state",
    "normalize_conditions",
    "prerequisites",
    "propose_action",
    "propose_dependency_candidates",
    "public_state",
    "reconcile_ordered_judgments",
    "resolve_state_path",
    "resolved",
    "save_state",
    "schedule_swiss_pairs",
    "select_diverse_finalists",
    "serialize_condition",
    "slugify",
    "truth",
    "unlock_items",
    "unlock_report",
    "universe",
    "unresolved",
]
